services:
  - type: web
    name: crypto-signals
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port 10000
    envVars:
      - key: BINANCE_API_KEY
        value: your_binance_api_key
      - key: BINANCE_API_SECRET
        value: your_binance_api_secret
      - key: TELEGRAM_TOKEN
        value: your_telegram_bot_token
      - key: TELEGRAM_CHAT_ID
        value: your_telegram_chat_id