services:
  - type: web
    name: crypto-signals-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
